### PR TITLE
Retry opening the dialog modal until it appears

### PR DESCRIPTION
**Pull request by adrianclay**
We've seen some flakeyness around the modal box not appearing after
the link to open it being clicked.  We believe this happens when the
link is clicked before bootstrap has registered the modal event handler.

Now we'll repeatedly open up the modal until the confirmation button
appears on the page.

### CODE REVIEW

**Comment by adrianclay** [comment]
Thanks to @nickcolley for reporting this.  :1st_place_medal:

**Comment by kevindew** [comment]
Thanks for digging into this 💯 

We shouldn't need to do reloading though with capybara. I'll just dig some details out.

**Comment by kevindew** [comment]
here's a post: https://www.varvet.com/blog/why-wait_until-was-removed-from-capybara/

So I'm guessing what is happening here is that the link is on the page (and findable) then in theory it should also be waiting for the button to be there before it tries to click it? if it's not able to find it it should error - is that what's happening?

**Comment by kevindew** [comment]
Sorry, I jumped the gun a bit with comments as this is more complicated than I first thought. I agree it's not trivial to know what to wait for here.

I think there is a way you can do this though without having to set up the loop and venture into the `wait_until` world of Capybara. It actually doesn't matter whether the javascript is initialised or not as the form is on the page. So we might be able to do one of the following things:

```
within("#request_review_form", visible: :all) do
  click_button button
end
```

or 

```find("button", text: button, visible: :all).click```

They're both a bit messier than I thought would be (sad there isn't a `click_button button, visible: :all`)

**Comment by adrianclay** [comment]
@kevindew We've investigated trying to target and click the button without relying on the modal but are finding this to be unreliable (looks like a separate race condition).  Adding a sleep before trying to click the publish button did increase the success rate of these tests but not in a way we were happy with.

**Comment by kevindew** [comment]
@adrianclay ok no worries, can you add a comment about why we're having to circumvent capybara standard practices?

**Comment by adrianclay** [comment]
👍  Just pushed the comment.

**Pull request merged**
