### PR TITLE
Remove publish_eu_exit_business_finder task

### PR DESCRIPTION
**Pull request by huwd**
Trello: https://trello.com/c/qBM5QLID/482-remove-business-finder-tech-debt

This task has been removed, it's continued existence in e2e tests is leading to failures.

This PR removes it.

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Do we want the tasks above it too? I'm not sure where we are with facet tags and whether we have/are ripping them out

**Comment by huwd** [comment]
Yeah, i checked those, there's still stuff in content-tagger.
Going to go remove that stuff and put in a separate PR for anything `lib/data/find-eu-exit-guidance-business.yml` related.

**Comment by kr8n3r** [comment]
I guess this can go as well?
`rspec ./spec/content_tagger/tagging_to_business_finder_spec.rb:9 # Adding a facet tag to a finder content Adding a facet tag to a published document`

**Comment by huwd** [comment]
argh... yeah i made that a separate PR: https://github.com/alphagov/publishing-e2e-tests/pull/357
But they have each other's errors. will squash

**Comment by huwd** [comment]
🥁 ok should now pass...

**Pull request merged**
